# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7afbc63cb1889a3b7f823a56835965bba6fb6a5ef60af0a086524871b35ebe066cbeec6e9ab55fa14a5be1c3ebddaacc9c731e7be269a5535700dbc1ad63d130

test:
  secret_key_base: 46c5016487a6b400ba6fc33edbd594757e4238ab2300e1bfad9b0f9121c0ebf7f4a4c75c33277d5eef1c2415e9d9fd24f7645fe6f7686d774ee3024258d9ff04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
